[6주차 과제] 서버 통신 심화
GO-SOPT-ANDROID/haeun-lee pull request #11
Opened 2023-06-02 16:11 UTC by leeeha

- #10 

## 필수 과제 

- [x] Reqres API 통신에서 UI Layer 사용하기 (ViewModel, LiveData)
- [x] 회원가입 아이디, 비밀번호 조건에 맞지 않으면 경고 띄우기

## 심화 과제 

- [x] 기존에 작성된 코드를 UI Layer로 분리하기 
- [x] 양방향 데이터바인딩으로 코드 로직 개선 
- [x] HomeFragment, GalleryFragment 로딩 뷰 구현

## 도전 과제 

- [ ] Data Layer 분리 (Repository, DataSource) 

## 실행 결과 

https://github.com/GO-SOPT-ANDROID/haeun-lee/assets/68090939/d9c7f161-2ea6-4592-a58d-cf76e2767b55

## 리팩토링 TODO

- [x] LoadingDialogFragment로 로딩 뷰 구현해보기 
- [x] UiState에 Loading 추가해서 상태 관리하기 
- [x] LiveData map 사용해서 구현해보기 -> 데이터바인딩으로 에러 상태 표시 
- [x] EditText에 포커스가 놓이지 않았는데 error가 표시되는 문제 해결하기 
- [x] 정규표현식에서 아이디, 비밀번호의 최소/최대 길이 상수화 시키기

2023-06-05 01:00 UTC, b1urrrr requested changes
TextInputEditText 커스텀하기 좀 까다로운 걸로 알고 있는데 예쁘게 잘 구현하셨네요 😮
6주차도 과제 하시느라 고생하셨습니다 👍👍

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/main/gallery/GalleryFragment.kt
>                      getString(R.string.gallery_follower_list_null_msg)
Failure인 경우에도 LoadingDialog를 dismiss 해주는 것이 좋을 것 같습니다!

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpViewModel.kt
> +        val pwRegex = """^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^+\-=])[A-Za-z\d!@#$%^+\-=]{6,12}$"""
```suggestion
        val pwRegex = """^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^+\-=])[A-Za-z\d!@#$%^+\-=]{MIN_PW_LENGTH,MAX_PWD_LENGTH}$"""
```
정규식에 상수를 사용하는 것이 보일러플레이트를 줄일 수 있을 것 같습니다!

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpViewModel.kt
> +        return isValidId() && isValidPw() && isNotBlankName() && isNotBlankHobby()
```suggestion
    fun isNotBlankName() = name.isNotBlank()

    fun isNotBlankHobby() = hobby.isNotBlank()

    fun isValidInput() = isValidId() && isValidPw() && isNotBlankName() && isNotBlankHobby()
```
single expression 함수로 구현하면 조금 더 깔끔할 것 같습니다!

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpActivity.kt
> +        }
TextChangedListener를 설정할 때 유사한 로직이 반복되고 있는데, InputEditText와 Boolean 타입의 조건을 인자로 받는 함수를 만들어 사용할 수도 있을 것 같습니다!

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/res/layout/activity_login.xml
> +                android:singleLine="true"
[singleLine 속성은 deprecated된 속성이기 때문에 `maxLines`를 활용](https://stackoverflow.com/questions/37080073/alternative-of-singleline-attribute-deprecated-textinputedittext)하는 것이 좋을 것 같습니다!

2023-06-05 01:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpActivity.kt
> +    }
이것도 데이터바인딩이나 바인딩 어댑터를 활용하여 처리하면 코드를 좀 줄일 수 있을 것 같습니다!

2023-06-05 19:37 UTC, lsakee reviewed
하은이 코드 너무 좋네~! 배워갑니다 !

2023-06-05 19:37 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpActivity.kt
> +        }
한개로 합칠수 있을거 같습니다

2023-06-11 10:03 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpActivity.kt
> +    }
데이터 바인딩으로 어떻게 구현할 수 있을까요?! 힌트 좀 더 주시면 감사하겠습니다 😂

2023-06-11 10:21 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignUpActivity.kt
> +        }
하나로 합치려면 어떻게 해야 될까요?! 힌트 주세요,,ㅎㅎ

2023-06-14 12:25 UTC, b1urrrr approved these changes
LGTM 💚
앱잼 화이팅~

2023-06-15 06:46 UTC, merged