[1주차 과제] 안드로이드 UI 구현 기초
GO-SOPT-ANDROID/haeun-lee pull request #2
Opened 2023-04-06 09:22 UTC by leeeha

- https://github.com/GO-SOPT-ANDROID/haeun-lee/issues/1
- 요구사항에 따라 이슈에 기능 목록을 작성하고, 개발하면서 계속 업데이트 하는 식으로 구현했습니다!
- 액티비티 생명주기는 내일까지 정리해서 링크 걸어둘 생각입니다!
- 금잔디 조원분들 코드리뷰 마음껏 달아주세요! 여러분의 피드백을 통해 더 나은 코드로 개선하고 싶어요! 

## 필수 과제 

- [x] 로그인 화면 
- [x] 회원가입 화면 
- [x] 홈 화면 (유저 정보 표시) 

## 심화 과제 

- [ ] 액티비티 생명주기 알아보기 
- [x] 조금 더 좋은 UX 제공하기 

## 도전 과제 

- [x] 자동 로그인 
- [x] 홈 화면에서 로그인 화면으로 다시 진입할 수 없도록 
- [ ] 자유 형태로 구현하기 

## 실행 결과 

- 에뮬레이터로 녹화해서 반응 속도가 좀 느려요,,
<img width="300" src="https://user-images.githubusercontent.com/68090939/230333049-0e4533c3-c267-4839-a678-c1efb72674c6.gif"/>

2023-04-07 13:06 UTC, b1urrrr requested changes
Issue에서 태스크를 정말 꼼꼼하게 나누셨네요!! 세밀한 To-do 작성을 기반으로 원자적 커밋을 할 수 있기 때문에 정말 좋은 습관인 것 같습니다 👏👏
code reformat 단축키(Window 기준 Ctrl + Alt + L)도 자주 눌러주시면 더 좋을 것 같아요!
코드 수정해주시고 reviewers에서 re-request 해주시면 달려올게요 💨

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +    }
`onCreate()` 함수에 로직이 몰려 있는 것 같습니다!
함수화를 통해 로직을 분리해주시면 가독성도 좋아지고 onCreate의 역할을 덜어줄 수 있어 좋을 것 같습니다 🙃

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +                Toast.makeText(this, NOT_YET_REGISTERED_MSG, Toast.LENGTH_SHORT).show()
스낵바나 토스트를 발생시키는 함수는 프로젝트 전역에서 재사용될 수 있기 때문에 Activity나 Context, View의 확장함수를 사용하는 방법을 찾아보셔도 좋을 것 같습니다 :)
확장 함수 한번 만들어놓으면 코드량을 엄청 줄일 수 있기 때문에 굉장히 편리합니다!

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +        startActivity(intent)
```suggestion
        Intent(this, MainActivity::class.java).apply {
                    addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
                    startActivity(this)
                }
```
스코프 함수 `apply`나 `also`를 활용하여 코틀린스럽게 작성할 수도 있습니다 ㅎㅎ

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +        binding.tvHobby.text = "특기: $hobby"
```suggestion
        binding.tvName.append(name)
        binding.tvHobby.append(hobby)
```
`append()` 함수를 활용하여 좀 더 간결하게 작성할 수도 있습니다!

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/signup/SignUpActivity.kt
> +    }
```suggestion
    private fun getAllInputValues(): User {
        val id = binding.etId.text.toString()
        val pw = binding.etPw.text.toString()
        val name = binding.etName.text.toString()
        val hobby = binding.etHobby.text.toString()
        return User(id, pw, name, hobby)
    }
```
Data Class로 정의하신 User 클래스를 활용해보는 건 어떨까요?

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/signup/SignUpActivity.kt
> +        }
```suggestion
        binding.btnSignUp.setOnClickListener {
            val inputs = getAllInputValues()
            if(checkInputValidity(inputs)){
                val intent = Intent(this, LoginActivity::class.java).apply {
                    putExtra(ID_KEY, inputs[0])
                    putExtra(PW_KEY, inputs[1])
                    putExtra(NAME_KEY, inputs[2])
                    putExtra(HOBBY_KEY, inputs[3])
                }
                setResult(RESULT_OK, intent)
                finish()
                return@setOnClickListener
            }
            Toast.makeText(this, INVALID_INPUT_ERROR, Toast.LENGTH_SHORT).show()
        }
```
사람마다 코드 스타일이 다르지만 early return 패턴으로 작성할 수도 있습니다!

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/signup/SignUpActivity.kt
> +    }
상수 관리 꼼꼼하게 잘 하셨네요!! 👍👍

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/util/Messages.kt
> +const val INVALID_INPUT_ERROR = "모든 항목에 유효한 값을 입력해주세요."
UI에 표시되는 메시지 문자열들은 strings.xml에서 정의하여 사용하는 것이 리소스 사용량을 줄이고 유지보수가 용이할 것 같습니다! 
앱을 국제화하기 위해 다른 언어로 번역하여 지원하게 될 경우에도 편리할 것입니다 :)

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/res/layout/activity_login.xml
> +        android:text="Welcome to GO Android!"
귀찮긴 하지만 xml에서도 텍스트 추출로 보일러플레이트를 줄여봅시다!

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/res/layout/activity_main.xml
> +        tools:text="이름: "
위에서 설명드린 append 함수를 활용하게 된다면 `android:text` 속성을 활용하시면 될 것 같습니다!

2023-04-07 13:06 UTC, b1urrrr commented on app/src/main/res/values/colors.xml
> +    <color name="red">#F44336</color>
color까지 지정하시다니 👍👍
3주차 세미나 때 팟짱님이 알려주시겠지만 네이밍을 하실 때 [Material Design](https://m2.material.io/design/color/the-color-system.html#color-usage-and-palettes)을 참고하셔도 좋을 것 같아요 😉

2023-04-07 15:21 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/SignUpActivity.kt
> +            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
addTextChangedListener를 활용해 길이제한조건을 사용자에게 명시해주는 점 좋았습니다 😘

2023-04-07 15:21 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/SignUpActivity.kt
> +    private fun checkLengthOfPw(pw: String): Boolean {
함수명이 항상 기능을 직관적으로 잘명시되어있는 것 같습니다 ! 참고해야겠어용

2023-04-09 12:32 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +                    Toast.makeText(this, LOGIN_SUCCESS_MSG, Toast.LENGTH_SHORT).show()
토스트 메시지 분리 해도 될거 같아요!

2023-04-09 12:32 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +    private fun hideKeyboard() {
이기능도 util로 빼면 좋을거 같네요 !

2023-04-09 12:32 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/signup/SignUpActivity.kt
> +            } else {
에러체크까지 꼼꼼하시네요!

2023-04-10 10:37 UTC, b1urrrr approved these changes
LGTM 👍

2023-04-10 10:40 UTC, merged