[2주차 과제] 안드로이드 UI 구현 심화
GO-SOPT-ANDROID/haeun-lee pull request #4
Opened 2023-04-21 02:01 UTC by leeeha

#3 

## 필수 과제 

- [x] 리사이클러뷰 위에 있는 헤더가 같이 스크롤 되도록
  - Hint: Multi-View Type RecyclerView or ConcatAdapter 
  - HomeFragment 리사이클러뷰에 적용했습니다. (rv_home) 

## 심화 과제 

- [x] BottomNavigationView 버튼을 한번 더 누르면, 최상단으로 스크롤 되도록 (Scroll to top) 
  - Hint: BottomNavigation.setOnNavigationItemReselectedListener
  - HomeFragment, GalleryFragment에 있는 리사이클러뷰에 적용했습니다. 
- [x] [프래그먼트 생명주기 알아보기](https://velog.io/@jxlhe46/Android-Fragment-Lifecycle)
- [x] 리사이클러뷰 성능 개선하기 
  - notifyDataSetChanged 함수의 문제점을 개선한 DiffUtil + ListAdapter에 대해 알아보고 사용해보기
  - GalleryFragment 리사이클러뷰에 적용했습니다. (rv_gallery) 
- [ ] RecyclerView Selection 라이브러리 사용해보기 
  - Selection 라이브러리를 활용하여 아이템 다중 선택 시, 아이템 뷰에 선택 효과 주기 
  - 아이템 뷰의 특정 버튼 클릭 시, 아이템 삭제하기 
  - 이번 주말까지 구현해서 다시 push 보낼 예정입니다!! 

## 도전 과제 

- [ ] MotionLayout 이용해서 모션 및 위젯 애니메이션 넣어보기 
- [ ] (가짜) 서버통신 해보기 
  - kotlinx-serialization으로 JSON 데이터 파싱하여 HomeFragment 리스트에 넣기 

## 실행 결과

2023-04-23 09:07 UTC, lsakee approved these changes
배우고 갑니다 ㅎㅎ

2023-04-23 09:07 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/main/home/HomeFragment.kt
> +            layoutManager = LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
xml recycler view 속성에 layoutManager 이용하셔도 될거 같아요!

2023-04-23 09:07 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolder.kt
> +sealed class MultiViewHolder<E : MultiViewItem>(
sealed class 를 이용해서 하는 방법도 있군요 배워갑니다 ㅎ

2023-04-23 09:07 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +    private fun initBnvItemReselectedListener() {
세미나때 하신 말처럼 네이밍이 길어져도 훨씬 좋은 이름이네요 ! 네이밍하는 방법 배우겠습니다 ㅎ

2023-04-23 09:43 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/binding/BindingFragment.kt
> +abstract class BindingFragment<T : ViewDataBinding>(
바인딩 프래그먼트까지 ,,,,, 👍

2023-04-23 10:05 UTC, lsakee commented on app/src/main/res/layout/item_image.xml
> +            type="String" />
Repo data class 사용하셔도 될거 같습니다 !

2023-04-23 10:13 UTC, KwakEuiJin approved these changes

2023-04-23 10:13 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolder.kt
> +sealed class MultiViewHolder<E : MultiViewItem>(
정말 코드들하고 네이밍이 너무 좋아서 많이 배웠습니다ㅎㅎ

2023-04-23 10:40 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/binding/BindingFragment.kt
> +    }
큰 문제는 없겠지만, 부모의 onDestroyView가 뷰를 파괴하는 역할이므로, 그 위에 _binding 에 null을 넣어 해제해주는건 어떨까요?

2023-04-23 11:05 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +                    recyclerView.scrollToPosition(0)
요 부분에서 findViewById를 사용하지 않고도 가능할까요?

2023-04-23 11:18 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +                is HomeFragment -> {
여기서 item의 id로 프래그먼트를 접근하면 findById를 쓰지않을수있어서 코드양이 적어질 수 있을것같아요 !

2023-04-23 11:18 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolderFactory.kt
> +class MultiViewHolderFactory {
저는 sealed class로 해놓고 이 코드를 adapter에 전부 넣었는데 viewholderfactory를 이렇게 활용할 수 있군요 ! 저도 참고해서 리팩토링 해보겠습니다 !

2023-04-23 11:18 UTC, sxunea commented on app/src/main/res/menu/main_bnv_menu.xml
> +        android:title="Home" />
여기도 string resource 추출하면 더 좋을것같습니다 !

2023-04-23 11:23 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/GalleryFragment.kt
> +/** DiffUtil + ListAdapter 사용해서 리사이클러뷰 성능 개선하기 */
👍

2023-04-23 11:24 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/adapter/MyItemTouchHelperCallback.kt
> +        (recyclerView.adapter as MyListAdapter).moveItem(
위에서 말씀드린 findByViewId 없이 scroll to top 기능을 구현하는것의 힌트는 요것입니다 !

2023-04-23 11:26 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/ui/main/home/HomeFragment.kt
> +            layoutManager = LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
만약 XML에서 사용하실 경우 orientation도 반드시 지정해주셔야 한다는 점 !

2023-04-23 11:27 UTC, giovannijunseokim approved these changes
고수시군요,, 고생하셨습니다 !

2023-04-23 11:33 UTC, giovannijunseokim commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolder.kt
> +    data class TextViewHolder(
이 클래스를 data class로 만들어주신 이유가 무엇인가요?

2023-04-23 12:05 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/ui/main/home/HomeFragment.kt
> +            layoutManager = LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
다들 코멘트 감사합니다!!

2023-04-23 12:42 UTC, leeeha commented on app/src/main/res/layout/item_image.xml
> +            type="String" />
코멘트 참고해서 item_github_repo.xml은 삭제하고 item_image.xml 파일만 남겨뒀어요!

2023-04-23 12:58 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/binding/BindingFragment.kt
> +    }
공식문서 [코드](https://developer.android.com/topic/libraries/view-binding#fragments)를 다시 봤는데 아래처럼 작성되어 있더라구요..! 

프래그먼트 뷰가 종료되고 나서도 프래그먼트 객체는 살아있기 때문에, 바인딩으로 인한 메모리 누수를 막으려면 `_binding = null` 을 설정해줘야 한다는 것으로 알고 있습니다. 그래서 원래대로 작성해도 괜찮지 않을까 하는 게 제 개인적인 의견입니다..!

```kotlin 
private var _binding: ResultProfileBinding? = null
// This property is only valid between onCreateView and
// onDestroyView.
private val binding get() = _binding!!

override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View? {
    _binding = ResultProfileBinding.inflate(inflater, container, false)
    val view = binding.root
    return view
}

override fun onDestroyView() {
    super.onDestroyView()
    _binding = null
}
```

2023-04-23 13:04 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolder.kt
> +    data class TextViewHolder(
구글링해서 나온 코드를 거의 그대로 사용한 거여서,, 저도 무의식적으로 따라서 친 거 같아요😅 뷰홀더는 일반 클래스로 선언하는 게 좋을 거 같아요! 피드백 감사합니다👍👍

2023-04-23 13:06 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/adapter/MyItemTouchHelperCallback.kt
> +        (recyclerView.adapter as MyListAdapter).moveItem(
아 어댑터 내에 Scroll to top 기능을 구현하는 함수를 만들고 그걸 메인 액티비티에서 호출하면 될 거 같네요! 피드백 감사해요!!

2023-04-23 13:13 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolder.kt
> +sealed class MultiViewHolder<E : MultiViewItem>(
저도 이번에 구글링으로 처음 배운 코드들이 대부분인 거 같아요!! 온전히 제가 짠 코드는 아니라는 점,, 참고로 알아주세요!

2023-04-23 13:46 UTC, b1urrrr requested changes
직관적이고 효율적인 코드를 작성하려고 노력하시는 게 많이 느껴지네요 👍
이번 주도 과제 하시느라 고생하셨습니다 ~ 👏👏

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +    private fun initBnvItemReselectedListener() {
컴포넌트의 어떤 리스너를 초기화하는 것인지까지 명시해주니까 훨씬 직관적이네요! 센스 있는 네이밍 방식 배워갑니다 🤭

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +        }
```suggestion
        if (currentFragment == null) changeFragment(HomeFragment())
```

여기서도 `changeFragment` 함수를 활용할 수 있을 것 같습니다!

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +            .commit()
[Android KTX에서 제공되는 Fragment KTX](https://developer.android.com/kotlin/ktx?hl=ko)를 사용하면 코드를 경량화하고 불필요한 프래그먼트 객체 생성을 줄일 수 있습니다!
[공식문서의 FragmentTransaction 예시에서도 ktx를 활용하고 있습니다.](https://developer.android.com/guide/fragments/fragmentmanager#perform) 한번 참고해보시면 좋을 것 같아요 :)

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/adapter/MyDiffCallback.kt
> +}
제너릭을 활용하여 다른 ListAdapter를 구현할 때에도 재사용할 수 있도록 구현해봐도 좋을 것 같습니다!

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/adapter/MyItemTouchHelperCallback.kt
> +import org.android.go.sopt.ui.main.gallery.adapter.MyListAdapter
Optimize imports 단축키와 Reformat code 단축키를 습관화하여 사용하지 않는 import문은 제거하고 코드 가독성을 높이는 것을 추천 드립니다!
Window 기준 Optimize import는 `Ctrl + Alt + O`, Reformat code는 `Ctrl + Alt + L` 입니다.

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/gallery/adapter/MyItemTouchHelperCallback.kt
> +    }
`recyclerView.adapter as MyListAdapter`처럼 as를 활용한 강제 형변환은 예기치 못한 예외가 발생할 수 있기 때문에 지양하는 것이 좋다고 생각합니다. [대체할 수 있는 방법](https://thdev.tech/kotlin/2020/10/20/kotlin_effective_07/)이 뭐가 있을지 찾아보시는 것을 추천 드립니다 ㅎㅎ

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewAdapter.kt
> +    @Suppress("UNCHECKED_CAST")
이 어노테이션을 추가하신 이유가 뭘까요?
`@Suppress`로 컴파일 오류를 무시하기보다는 안전성을 보장하는 다른 방법을 찾아보는 것이 좋다고 생각합니다!

2023-04-23 13:46 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/home/adapter/MultiViewHolderFactory.kt
> +    }
```suggestion
import org.android.go.sopt.ui.main.home.adapter.MultiViewType.IMAGE
import org.android.go.sopt.ui.main.home.adapter.MultiViewType.TEXT

    fun getViewHolder(parent: ViewGroup, viewType: MultiViewType): MultiViewHolder<MultiViewItem> {
        return when (viewType) {
            TEXT ->
                MultiViewHolder.TextViewHolder(viewBind(parent, R.layout.item_text))
            IMAGE ->
                MultiViewHolder.ImageViewHolder(viewBind(parent, R.layout.item_image))
        } as MultiViewHolder<MultiViewItem>
    }
```

사람마다 코드 스타일이 다르지만 저는 상수값 임포트를 통해 코드를 간략화하는 편입니다!

2023-04-23 19:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +    }
```suggestion
    private fun initBnvItemSelectedListener() {
        binding.bnvMain.setOnItemSelectedListener { item ->
            when (item.itemId) {
                R.id.home_menu -> changeFragment(HomeFragment())
                R.id.gallery_menu -> changeFragment(GalleryFragment())
                R.id.search_menu -> changeFragment(SearchFragment())
                else -> false
            }
            true
        }
    }
```

이렇게 쓸 수도 있을 것 같아요!

2023-04-29 15:05 UTC, b1urrrr approved these changes
LGTM 👍

2023-04-30 03:29 UTC, merged

2023-05-02 09:01 UTC, Marchbreeze commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +    }
이 방법이 더 좋아보여 저도 scroll to top 기능 수정했어요 ㅎㅎ

2023-05-02 15:57 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/ui/main/MainActivity.kt
> +    }
엇 참고가 되었다니 다행이네요!! 제 코드에 관심 가져주셔서 감사합니다🙂