[3주차 과제] UI/UX의 이해와 구글의 머티리얼 디자인
GO-SOPT-ANDROID/haeun-lee pull request #6
Opened 2023-05-05 14:50 UTC by leeeha

- https://github.com/GO-SOPT-ANDROID/haeun-lee/issues/5
- 저번에 못했던 과제도 이어서 진행하고 있습니다! 

## 지난 과제 보충

- [x] SharedPreferences 비밀번호 데이터 [암호화](https://cliearl.github.io/posts/android/encrypted-sharedpreferences/) 하기 
- [ ] 깃헙 레포 JSON 데이터 파싱해서 리사이클러뷰에 적용하기 

## 심화 과제 

- [x] 더 아름다운 Color 적용하기 
  - [Full Screen UI with Transparent Status Bar](https://proandroiddev.com/android-full-screen-ui-with-transparent-status-bar-ef52f3adde63)
- [x] 더 아름다운 Font 적용하기 
  - [에스코어드림](https://noonnu.cc/font_page/223) 폰트 사용
  - [lineHeight](https://stackoverflow.com/questions/37754299/how-to-properly-set-line-height-for-android) 속성 조정하기 

## 도전 과제 

- [x] 마이페이지에 유저 정보 표시 
- [ ] 마이페이지에 로그아웃 다이얼로그 창 구현 
- [ ] 더 다양한 뷰들 알아보기

2023-05-05 19:40 UTC, b1urrrr requested changes
이번 주차도 과제하시느라 고생하셨습니다 👏👏

2023-05-05 19:40 UTC, b1urrrr commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.10.0'
[팟장님 과제에 의진님께서 남겨주신 리뷰](https://github.com/GO-SOPT-ANDROID/junseo-kim/pull/1#discussion_r1178782978)를 그대로 가져왔습니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/70993562/236547491-543201b6-966e-40fe-baf5-f9e0b8fe572c.png)

[종속성 트리](https://stackoverflow.com/questions/62789101/why-some-projects-import-androidx-activity-ktx-or-not)에 포함되어 있어서 아래 dependency 만 사용하셔도 된다고 합니다!
```
 implementation 'androidx.fragment:fragment-ktx:1.5.7
```

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/data/DataSources.kt
> +            add(Header("Repository List"))
얘도 strings.xml로 추출해도 좋을 것 같아요!

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/util/PreferenceUtil.kt
> +        private const val FILE_NAME = "encrypted_user_info"
와 이거까지 상수화하셨네요!
진짜 꼼꼼하십니다 👍

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/util/PreferenceUtil.kt
> +        sharedPreferences.edit().clear().apply()
```suggestion
    fun putString(@StringRes keyId: Int, newValue: String) {
        val key = context.getString(keyId)
        sharedPreferences.edit() { putString(key, newValue) }
    }

    fun deleteAllData() {
        sharedPreferences.edit { clear() }
```

[Android KTX](https://developer.android.com/kotlin/ktx)를 활용하여 조금 더 코드를 경량화할 수도 있습니다!
[Google Developers 블로그 글 SharedPreferences 편집 부분](https://developers-kr.googleblog.com/2018/02/introducing-android-ktx-even-sweeter-kotlin-development-for-android.html)을 참고해주세요 :)

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/res/layout/item_header.xml
> +            android:layout_width="match_parent"
저도 이번에 싹 바꿨는데 constraintLayout 내부 컴포넌트들은 0dp를 활용하는 것이 권장된다고 합니다!

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/res/values/themes.xml
> +        <item name="textAppearanceLabelMedium">@style/TextAppearance.GOSOPTAndroid.LabelMedium</item>
크으 textAppearance까지 깔끔하게 커스텀하셨네요 👍

2023-05-05 19:40 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/ui/login/LoginActivity.kt
> +        }
Serializable을 활용하여 데이터 클래스 객체를 넘겨준 점 너무 좋습니다 🤭
대체로 Serializable보다 성능이 좋은 [Parcelable](https://www.charlezz.com/?p=823)도 한번 찾아보시는 걸 추천 드려요 :)

2023-05-07 08:53 UTC, lsakee reviewed
고생하셨습니당!

2023-05-07 08:53 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/ui/main/mypage/MyPageFragment.kt
> +    }
dialog까지 과제 열심히 하시네요

2023-05-07 08:53 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/util/PreferenceUtil.kt
> +            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
encrted까지 하셨군요 !

2023-05-08 08:03 UTC, b1urrrr approved these changes
LGTM 👍👍

2023-05-10 14:28 UTC, merged